### ISSUE TITLE
Throws an exception UnknownSignInWithAppleException

### ISSUE THREAD

**Issue by abdussamad0** [aboutyou/dart_packages#111]
Getting this exception when I added activity into AndroidManifest.xml file and hit sign in with apple button.
Unhandled Exception: UnknownSignInWithAppleException(MISSING_ACTIVITY, Plugin is not attached to an activity

Is there any configuration issue?

**Comment by HenriBeck** [comment]
@abdussamad0 could you please provide the output of `flutter doctor -v`, our plugin version, and whether or not you are using the Android V2 Embedding.

**Comment by kevincherryholme** [comment]
@HenriBeck 
I am getting this exact issue too. I have been fighting with this issue for a few days. I've copied the example project from the plugin, and it works fine, however, my project gets "Plugin is not attached to an activity":

```
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter (12928): The following UnknownSignInWithAppleException was thrown:
I/flutter (12928): UnknownSignInWithAppleException(MISSING_ACTIVITY, Plugin is not attached to an activity, {url:
I/flutter (12928): https://appleid.apple.com/auth/authorize?client_id=com.aboutyou.dart_packages.sign_in_with_apple.example&redirect_uri=https%3A%2F%2Fflutter-sign-in-with-apple-example.glitch.me%2Fcallbacks%2Fsign_in_with_apple&scope=email+name&response_type=code+id_token&response_mode=form_post&nonce=example-nonce&state=example-state})
```

I am currently using version:
```
sign_in_with_apple: ^2.5.1
```

flutter doctor -v output:
```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.900], locale en-CA)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (10 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\KevinCherryholme\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.46.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

Additionally, here is the list of plugins I've got:
```
flutter_bloc: ^3.2.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.1
  flutter_facebook_login: ^3.0.0
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.15
  ads: ^1.7.3 # Adds 1 MB to final apk size
  cupertino_icons: ^0.1.3
  sqflite: ^1.2.0
  shared_preferences: ^0.5.6+1
  path_provider: ^1.5.1
  date_format: ^1.0.8
  charts_flutter: ^0.9.0
  screen: ^0.0.5
  package_info: ^0.4.0+13
  cached_network_image: ^2.0.0-rc
  timeago: ^2.0.20
  auto_size_text: ^2.1.0
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  confetti: ^0.3.0
  introduction_screen: ^1.0.8
  reorderables: ^0.3.2
  uuid: ^2.0.4
  flutter_signin_button: ^1.0.0
  data_connection_checker: ^0.3.4
  flutter_password_strength: ^0.1.4
  badges: ^1.1.1
  profanity_filter: ^1.0.2
  duration: ^2.0.11
  random_color: ^1.0.5
  flushbar: ^1.10.2
  flutter_colorpicker: ^0.3.4
  font_awesome_flutter: ^8.8.1
  flutter_local_notifications: ^1.4.4+1
  soundpool: ^1.1.0
  animations:
    git:
      url: git://github.com/flutter/packages.git
      path: packages/animations
```

What is Android V2 Embedding?
Thanks for the help!
